
import javax.swing.*;

public class EventFrame extends javax.swing.JFrame {

    private EventCollection evtCollection = new EventCollection().readFromFile();

    public EventFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectList = new javax.swing.JList<>();
        eventTitleBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addProject = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventList = new javax.swing.JList<>();
        addNewStudentLabel1 = new javax.swing.JLabel();
        selectedProject = new javax.swing.JLabel();
        saveEvent = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        evtDetailBox = new javax.swing.JTextArea();
        addNewStudentLabel2 = new javax.swing.JLabel();
        toEventBox = new javax.swing.JTextField();
        addNewStudentLabel3 = new javax.swing.JLabel();
        addProjectBox = new javax.swing.JTextField();
        registerEvent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Projects");

        projectList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        projectList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                projectListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(projectList);

        eventTitleBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Event Details");

        addProject.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addProject.setText("Add Project");
        addProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Events");

        eventList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eventList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                eventListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(eventList);

        addNewStudentLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addNewStudentLabel1.setText("New Event Title:");

        selectedProject.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        saveEvent.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        saveEvent.setText("Save Events");
        saveEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEventActionPerformed(evt);
            }
        });

        evtDetailBox.setColumns(20);
        evtDetailBox.setRows(5);
        jScrollPane4.setViewportView(evtDetailBox);

        addNewStudentLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addNewStudentLabel2.setText("Add Project:");

        toEventBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        addNewStudentLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        addNewStudentLabel3.setText("To Event:");

        addProjectBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        registerEvent.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        registerEvent.setText("Register Event");
        registerEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(addNewStudentLabel2)
                    .addComponent(addNewStudentLabel3)
                    .addComponent(addProjectBox, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addNewStudentLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addProject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedProject))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registerEvent)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(eventTitleBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(toEventBox, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addNewStudentLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventTitleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addNewStudentLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addProjectBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addNewStudentLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toEventBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(selectedProject)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProject)
                            .addComponent(registerEvent)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(saveEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectActionPerformed

        String projectName = addProjectBox.getText();
        String eventTitle = toEventBox.getText();
        Project newProject = null;
        ProjectCollection studentProject = ProjectFile.extractProjectDataFromFile();
        // extract project object with respect to project to be added
        for (int i = 0; i < studentProject.getNumOfProjects(); i++) {
            Project proj = (Project) studentProject.getProject(i);
            if (projectName.equals(proj.getTitle())) {
                newProject = proj;
            }
        }
        // extract event object with respect to project adding to the event
        for (int i = 0; i < evtCollection.getNumOfEvents(); i++) {
            if (eventTitle.equals(evtCollection.getEvent(i).getEventTitle())) {
                evtCollection.getEvent(i).addProject(newProject);
            }
        }
        // Reset
        evtDetailBox.setText("");
        eventTitleBox.setText("");
        // Populate eventDetails 
        for (int i = 0; i < evtCollection.getNumOfEvents(); i++) {
            Event temp = evtCollection.getEvent(i);
            setupEventDetails(temp, i + 1);
        }

    }//GEN-LAST:event_addProjectActionPerformed

    private void saveEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEventActionPerformed
        // Save  === write to file
        evtCollection.writeFromFile();
    }//GEN-LAST:event_saveEventActionPerformed

    private void projectListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_projectListValueChanged
        String project = projectList.getSelectedValue();
        addProjectBox.setText(project);
    }//GEN-LAST:event_projectListValueChanged

    private void eventListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_eventListValueChanged
        String event = eventList.getSelectedValue();
        toEventBox.setText(event);
    }//GEN-LAST:event_eventListValueChanged

    private void registerEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEventActionPerformed

        String evtTitle = eventTitleBox.getText();
        Project[] proj = new Project[0];
        if (!(evtTitle.equals(""))) {
            Event event = new Event(proj, evtTitle);
            evtCollection.addEvent(event);
            //Reset
            evtDetailBox.setText("");
            eventTitleBox.setText("");
            // Populate event details
            DefaultListModel evtDemoList = new DefaultListModel();
            for (int i = 0; i < evtCollection.getNumOfEvents(); i++) {
                Event temp = evtCollection.getEvent(i);
                setupEventDetails(temp, i + 1);
                evtDemoList.addElement(temp.getEventTitle());
            }
            eventList.setModel(evtDemoList);
        }
    }//GEN-LAST:event_registerEventActionPerformed

    public static void setupForm() {
        // Project
        ProjectCollection studentProject = ProjectFile.extractProjectDataFromFile();
        DefaultListModel demoList = new DefaultListModel();
        for (int i = 0; i < studentProject.getNumOfProjects(); i++) {
            Project temp = (Project) studentProject.getProject(i);
            demoList.addElement(temp.getTitle());
        }
        projectList.setModel(demoList);

        // Event 
        EventCollection evtCollection = new EventCollection();
        DefaultListModel evtDemoList = new DefaultListModel();
        evtCollection.readFromFile();

        // Popuate eventDetail Box
        for (int i = 0; i < evtCollection.getNumOfEvents(); i++) {
            Event temp = evtCollection.getEvent(i);
            setupEventDetails(temp, i + 1);
            evtDemoList.addElement(temp.getEventTitle());
        }
        eventList.setModel(evtDemoList);

    }

    // populate Event detail method
    private static void setupEventDetails(Event evt, int num) {
        String evtDetails = "Event " + num + "           " + evt.getEventTitle() + "\n";
        String projDetails = "";

        if (evt.getProjects() != null) {
            for (int i = 0; i < evt.getProjects().length; i++) {
                String projTitle = evt.getProjects()[i].getTitle();
                String projSchool = evt.getProjects()[i].getSchool();
                String projSupervisor = evt.getProjects()[i].getSupervisor();
                projDetails += "  " + (i + 1) + ":  " + projTitle + "      " + projSchool + "       " + projSupervisor + "\n";
            }
        }
        evtDetailBox.setText(evtDetailBox.getText() + (evtDetails + projDetails));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewStudentLabel1;
    private javax.swing.JLabel addNewStudentLabel2;
    private javax.swing.JLabel addNewStudentLabel3;
    private javax.swing.JButton addProject;
    private javax.swing.JTextField addProjectBox;
    private static javax.swing.JList<String> eventList;
    private javax.swing.JTextField eventTitleBox;
    private static javax.swing.JTextArea evtDetailBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private static javax.swing.JList<String> projectList;
    private javax.swing.JButton registerEvent;
    private javax.swing.JButton saveEvent;
    private javax.swing.JLabel selectedProject;
    private javax.swing.JTextField toEventBox;
    // End of variables declaration//GEN-END:variables
}
